### ISSUE TITLE
Rename BOT_API_ROOT and add it into sample .env file

### ISSUE THREAD

**Issue by iamfeek** [SGTinkers/msocietybot#20]
## Problem
`BOT_API_ROOT` is used in app.ts to instantiate Telegraf. 

There is a ternary here that assumes `BOT_API_ROOT` in `process.env` is for Telegram specifically. 
I believe that this can be cleaner. 
https://github.com/SGTinkers/msocietybot/blob/9666e5b707beb52e474a5351afa372e2bc3389b0/src/app.ts#L11-L14
I was also considering the fact that maybe it is a project-wide known fact that Telegram will be our only supported bot platform. Even with that argument, I dont see why we should not be explicit with it. 

## Proposal
**First proposal:** Rename `BOT_API_ROOT` to `TELEGRAM_BOT_API_ROOT` for better clarity.
**Second proposal:** Add `TELEGRAM_BOT_API_ROOT` to .env.sample

Lets discuss about whether or not we want to have the Telegram be the only supported bot platform. If that is the case, then we can ignore Proposal 1 and just go with Proposal 2.

**Comment by ruqqq** [comment]
Closing this as in my local branch, I am removing this env. Was previously introduced because mock-server was a candidate.
